### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by darkdragon-001** [eidottermihi/dependabot-gitlab-openshift#1]
There is no `LICENSE` file in this repository. This makes it difficult for other to re-use the contents of this repository. See https://choosealicense.com/no-permission/ on why this is a problem.

**Comment by klml** [comment]
@eidottermihi since you are the main developer, please licence the repository and our [internal clone](https://github.com/it-at-m/dependabot-gitlab-openshift) with [our preferred MIT](https://opensource.muenchen.de/licenses.html#own-developments), regardless of the fact that we archive the repo.

**Comment by eidottermihi** [comment]
LICENSE is added on https://github.com/it-at-m/dependabot-gitlab-openshift
